backend:
  name: github
  repo: maks02-11/autosite
  branch: main

  base_url: https://autosymptoms.net
  auth_endpoint: /api/auth
  
site_url: https://autosymptoms.net

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }